title: Txxt.is
description: Text and writing projects
baseurl: "" # the subpath of your site
url: "https://txxt.is" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
# Theme settings
sass:
  style: compressed
  sass_dir: _sass
